import { jsPDF } from 'jspdf'
import { format } from 'date-fns'

const COLORS = {
  G: [52, 211, 153],
  W: [248, 113, 113],
  M: [96, 165, 250],
}

export function generateWorkoutPDF(workout) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  const pageWidth = doc.internal.pageSize.getWidth()
  let y = 20

  // ─── Header ─────────────────────────────────────────
  doc.setFillColor(0, 0, 0)
  doc.rect(0, 0, pageWidth, 45, 'F')

  doc.setFont('helvetica', 'bold')
  doc.setFontSize(22)
  doc.setTextColor(255, 255, 255)
  doc.text('WOD ARCHITECT', 15, y + 2)

  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)
  doc.setTextColor(180, 180, 180)
  doc.text(format(new Date(workout.date), 'EEEE, MMMM d, yyyy'), 15, y + 10)

  // Type badge
  doc.setFontSize(11)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(255, 255, 255)
  const typeText = workout.type.toUpperCase()
  const typeWidth = doc.getTextWidth(typeText) + 10
  doc.setFillColor(60, 60, 60)
  doc.roundedRect(pageWidth - 15 - typeWidth, y - 2, typeWidth, 9, 2, 2, 'F')
  doc.text(typeText, pageWidth - 15 - typeWidth + 5, y + 4.5)

  y = 55

  // ─── Exercises Table ────────────────────────────────
  doc.setFontSize(13)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(30, 30, 30)
  doc.text('Exercises', 15, y)
  y += 8

  // Table header
  doc.setFillColor(245, 245, 245)
  doc.rect(15, y - 1, pageWidth - 30, 8, 'F')
  doc.setFontSize(8)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor(120, 120, 120)
  doc.text('MOD', 18, y + 4)
  doc.text('EXERCISE', 32, y + 4)
  doc.text('SETS', 110, y + 4)
  doc.text('REPS', 130, y + 4)
  doc.text('LOAD', 150, y + 4)
  y += 10

  // Table rows
  doc.setFont('helvetica', 'normal')
  doc.setFontSize(10)

  workout.exercises.forEach((ex, i) => {
    if (y > 265) {
      doc.addPage()
      y = 20
    }

    // Alternating row bg
    if (i % 2 === 0) {
      doc.setFillColor(250, 250, 250)
      doc.rect(15, y - 4, pageWidth - 30, 9, 'F')
    }

    // Modality dot
    const [r, g, b] = COLORS[ex.modality] || [180, 180, 180]
    doc.setFillColor(r, g, b)
    doc.circle(21, y - 0.5, 2.5, 'F')
    doc.setFontSize(6)
    doc.setTextColor(255, 255, 255)
    doc.text(ex.modality, 19.5, y + 1)

    // Exercise data
    doc.setFontSize(10)
    doc.setTextColor(30, 30, 30)
    doc.setFont('helvetica', 'normal')
    doc.text(ex.name, 32, y)

    doc.setTextColor(80, 80, 80)
    doc.text(String(ex.sets), 113, y)
    doc.text(String(ex.reps), 133, y)
    doc.text(ex.weight || '-', 150, y)

    y += 9
  })

  y += 5

  // ─── Notes ──────────────────────────────────────────
  if (workout.notes) {
    if (y > 250) {
      doc.addPage()
      y = 20
    }

    doc.setFontSize(13)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor(30, 30, 30)
    doc.text('Notes', 15, y)
    y += 7

    doc.setFontSize(9)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor(80, 80, 80)
    const lines = doc.splitTextToSize(workout.notes, pageWidth - 30)
    doc.text(lines, 15, y)
    y += lines.length * 5
  }

  // ─── Footer ─────────────────────────────────────────
  const totalPages = doc.internal.getNumberOfPages()
  for (let p = 1; p <= totalPages; p++) {
    doc.setPage(p)
    doc.setFontSize(7)
    doc.setTextColor(180, 180, 180)
    doc.text(
      'Generated by WOD Architect',
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 8,
      { align: 'center' },
    )
  }

  return doc
}

export function downloadWorkoutPDF(workout) {
  const doc = generateWorkoutPDF(workout)
  const dateStr = format(new Date(workout.date), 'yyyy-MM-dd')
  doc.save(`WOD_${workout.type.replace(/\s/g, '-')}_${dateStr}.pdf`)
}
